version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testAzertyuiop
    command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 test testAzertyuiop;
      /usr/bin/mc mb myminio/bucket-test;
      /usr/bin/mc policy set public myminio/bucket-test;
      exit 0;
      "
volumes:
  minio_storage: {}
 